version: '3.8'

services:
  db:
    image: "mysql:${MYSQL_VERSION}"
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3695:3306

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - ./:/var/www/app:rw

  web:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9095:80"